// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvtqrcqmdzpcfaquirhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2dHFyY3FtZHpwY2ZhcXVpcmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODA2NzcsImV4cCI6MjA4NTM1NjY3N30.HR0EYCyxL7YBhqiWeKgbNfJT1uMHgeo6eNgaf_VQWaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});